#!/usr/bin/env bash
set -uo pipefail  # Removed -e to allow graceful error handling

# Render SVG files from a LilyPond file
# Generates: <tune>_page_1.svg, <tune>_page_2.svg, etc.
#
# SVGs are processed to use currentColor for CSS theming
#
# Failed files are logged to TODO-List_Fix-Failed-LilyPond-Files.md

show_help() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS] file.ly

Render a LilyPond score to SVG files.

Output naming: <basename>_page_1.svg, <basename>_page_2.svg, etc.

Options:
  --help              Show this help.
  --force             Force regeneration even if SVG is up to date.

The script checks timestamps and only regenerates if the .ly file is newer
than existing SVG files (unless --force is used).

If compilation fails, the file is logged to TODO-List_Fix-Failed-LilyPond-Files.md
and a summary is printed at the end.

The SVG is processed to support CSS theming:
  - Black strokes/fills are replaced with 'currentColor'
  - This allows the parent element's color to control the SVG

Examples:
  $(basename "$0") my-tune.ly
  # Outputs: my-tune_page_1.svg (and _page_2.svg, etc. if multi-page)

  $(basename "$0") --force my-tune.ly
  # Force regeneration even if SVGs are up to date

Requires:
  - lilypond
  - sed
EOF
}

if [ $# -eq 0 ]; then
  show_help
  exit 1
fi

# --- Parse options ---
FORCE_REGENERATE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help)
      show_help
      exit 0
      ;;
    --force)
      FORCE_REGENERATE=true
      shift
      ;;
    -*)
      echo "Unknown option: $1" >&2
      show_help
      exit 1
      ;;
    *)
      LY_FILE="$1"
      shift
      break
      ;;
  esac
done

if [ -z "${LY_FILE:-}" ]; then
  echo "Error: no .ly file provided." >&2
  exit 1
fi

if [ ! -f "$LY_FILE" ]; then
  echo "Error: file not found: $LY_FILE" >&2
  exit 1
fi

# --- Check dependencies ---
command -v lilypond >/dev/null 2>&1 || { echo "Error: lilypond not found in PATH."; exit 1; }

BASENAME="$(basename "$LY_FILE" .ly)"
DIRNAME="$(dirname "$LY_FILE")"

# --- Check if regeneration is needed ---
# Check if SVG files exist and are newer than the .ly file
NEEDS_REGENERATION=false

if [ "$FORCE_REGENERATE" = true ]; then
  NEEDS_REGENERATION=true
  echo "Force regeneration enabled."
else
  # Check for single page SVG
  if [ -f "${DIRNAME}/${BASENAME}_page_1.svg" ]; then
    # SVG exists, check if .ly file is newer
    if [ "$LY_FILE" -nt "${DIRNAME}/${BASENAME}_page_1.svg" ]; then
      NEEDS_REGENERATION=true
    fi
  else
    # No SVG exists, need to generate
    NEEDS_REGENERATION=true
  fi

  if [ "$NEEDS_REGENERATION" = false ]; then
    echo "✓ SVG files are up to date (${BASENAME}_page_*.svg)"
    exit 0
  fi
fi

# Use a unique temp directory to avoid conflicts
TEMP_DIR=$(mktemp -d)
TEMP_BASE="${TEMP_DIR}/${BASENAME}"

# Get the repository root (go up from script location)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
TODO_FILE="${REPO_ROOT}/TODO-List_Fix-Failed-LilyPond-Files.md"

# Initialize TODO file if it doesn't exist
if [ ! -f "$TODO_FILE" ]; then
  {
    echo "# Failed LilyPond Files"
    echo ""
    echo "This file tracks LilyPond files that failed to compile to SVG."
    echo "Generated by: \`scripts/make-score-preview-svg.sh\`"
    echo ""
    echo "---"
  } > "$TODO_FILE"
fi

echo "Rendering SVG with LilyPond..."
#lilypond -fsvg --loglevel=ERROR -dno-midi -o "$TEMP_BASE" "$LY_FILE" 2>/dev/null

# Capture both stdout and stderr, and check exit status
LILY_OUTPUT=$(lilypond -fsvg -dno-midi -o "$TEMP_BASE" "$LY_FILE" 2>&1)
LILY_EXIT_CODE=$?

if [ $LILY_EXIT_CODE -ne 0 ]; then
  echo "✗ Error: LilyPond compilation failed for $LY_FILE"
  echo "  Exit code: $LILY_EXIT_CODE"

  # Get absolute path for the file
  ABS_LY_FILE="$(cd "$(dirname "$LY_FILE")" && pwd)/$(basename "$LY_FILE")"

  # Log to TODO file
  {
    echo ""
    echo "## Failed: $(basename "$LY_FILE") - $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "File: \`$ABS_LY_FILE\`"
    echo ""
    echo "Error:"
    echo '```'
    echo "$LILY_OUTPUT" | tail -20  # Last 20 lines of error
    echo '```'
    echo ""
    echo "---"
  } >> "$TODO_FILE"

  echo "  Logged to: $TODO_FILE"

  # Clean up and exit with error
  rm -rf "$TEMP_DIR"
  exit 1
fi

# Process SVG to make it CSS-themeable
process_svg() {
  local input="$1"
  local output="$2"
  sed -e 's/fill="#000000"/fill="currentColor"/g' \
      -e 's/fill="#000"/fill="currentColor"/g' \
      -e 's/fill:black/fill:currentColor/g' \
      -e 's/fill="black"/fill="currentColor"/g' \
      -e 's/stroke="#000000"/stroke="currentColor"/g' \
      -e 's/stroke="#000"/stroke="currentColor"/g' \
      -e 's/stroke:black/stroke:currentColor/g' \
      -e 's/stroke="black"/stroke="currentColor"/g' \
      "$input" > "$output"
}

# Find and process output SVGs
# LilyPond generates: basename.svg (single) or basename-1.svg, basename-2.svg (multi-page)
PAGE_COUNT=0

if [ -f "${TEMP_BASE}.svg" ]; then
  # Single page output
  PAGE_COUNT=1
  OUTPUT_FILE="${DIRNAME}/${BASENAME}_page_1.svg"
  echo "Processing page 1..."
  process_svg "${TEMP_BASE}.svg" "$OUTPUT_FILE"
  echo "  Created: $OUTPUT_FILE"
elif [ -f "${TEMP_BASE}-1.svg" ]; then
  # Multi-page output
  echo "Multi-page score detected."
  for svg_file in "${TEMP_BASE}"-*.svg; do
    # Extract page number from filename (e.g., basename-1.svg -> 1)
    # Use parameter expansion instead of sed to avoid regex issues with special chars
    temp_name=$(basename "$svg_file" .svg)
    PAGE_NUM="${temp_name#"${BASENAME}-"}"
    OUTPUT_FILE="${DIRNAME}/${BASENAME}_page_${PAGE_NUM}.svg"
    echo "Processing page ${PAGE_NUM}..."
    process_svg "$svg_file" "$OUTPUT_FILE"
    echo "  Created: $OUTPUT_FILE"
    PAGE_COUNT=$((PAGE_COUNT + 1))
  done
else
  echo "✗ Error: no SVG output found from LilyPond." >&2

  # Get absolute path for the file
  ABS_LY_FILE="$(cd "$(dirname "$LY_FILE")" && pwd)/$(basename "$LY_FILE")"

  # Log to TODO file
  {
    echo ""
    echo "## Failed: $(basename "$LY_FILE") - $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "File: \`$ABS_LY_FILE\`"
    echo ""
    echo "Error: No SVG output generated by LilyPond (compilation may have succeeded but produced no output files)"
    echo ""
    echo "---"
  } >> "$TODO_FILE"

  echo "  Logged to: $TODO_FILE"

  rm -rf "$TEMP_DIR"
  exit 1
fi

# Clean up temp directory
rm -rf "$TEMP_DIR"

echo "Done: Generated ${PAGE_COUNT} page(s)"
echo "  SVGs use 'currentColor' - set color via CSS to theme them."
